# Generated by Django 3.0.3 on 2020-03-14 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general_journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_general_journal.Head')),
            ],
            options={
                'unique_together': {('head', 'title')},
                'index_together': {('head', 'title')},
            },
        ),
    ]
