# Generated by Django 3.0.3 on 2020-03-14 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general_journal', '0003_accountsubhead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsubhead',
            old_name='sub_head',
            new_name='subhead',
        ),
        migrations.AlterUniqueTogether(
            name='accountsubhead',
            unique_together={('subhead', 'title')},
        ),
        migrations.AlterIndexTogether(
            name='accountsubhead',
            index_together={('subhead', 'title')},
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.DateField()),
                ('entry_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('account_subhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_general_journal.AccountSubHead')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_general_journal.Head')),
                ('subhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_general_journal.SubHead')),
            ],
        ),
    ]
