# Generated by Django 3.0.3 on 2020-03-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general_journal', '0004_auto_20200314_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubhead',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='head',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='subhead',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
